
--Connection TPA

--EMPLOYEES RECORDS--
select emp.hire_date, emp.adjusted_hire_date, EMP.HR_CODE, EMP.CREATION_SOURCE, EMP.PAYROLL_DATE, EMP.SOCIAL_SECURITY_NUMBER, emp.employee_type, emp.hours,
EMP.* from EMPLOYEES EMP 
where EMP.SOCIAL_SECURITY_NUMBER = '<SSN>'
order by EMP.SOCIAL_SECURITY_NUMBER, EMP.PAYROLL_DATE;


--EMPLOYERS RECORDS--
select ER.* from EMPLOYERS ER join EMPLOYEES EE on ER.EMPLOYEE_UUID = EE.EMPLOYEE_UUID
where 1=1
and ee.social_security_number = '<SSN>'
order by EE.SOCIAL_SECURITY_NUMBER, EE.PAYROLL_DATE;


--PAYROLLS INFO--
select P.* from PAYROLLS P  join employees emp on p.payroll_uuid = emp.payroll_uuid
where emp.social_security_number like '<SSN>'
order by P.PAYROLL_DATE;


--PAYROLL DATA--
select EMP.SOCIAL_SECURITY_NUMBER, EMP.PAYROLL_DATE, PD.DISPLAY_NAME, PD.column_value, PD.CODE, PP.PLAN_XSID, PD.* 
from PAYROLL_DATA PD join EMPLOYEES EMP on PD.EMPLOYEE_UUID = EMP.EMPLOYEE_UUID 
join PAYROLL_PLANS PP on PP.PLAN_UUID = EMP.PLAN_UUID 
where EMP.SOCIAL_SECURITY_NUMBER in ('<SSN>')
and PD.CODE is not null
order by EMP.SOCIAL_SECURITY_NUMBER, EMP.PAYROLL_DATE, PD.EMPLOYEE_UUID, PD.DISPLAY_NAME; 


--PAYROLL DATA HISTORY--
select EMP.PAYROLL_DATE, EMP.SOCIAL_SECURITY_NUMBER, PD.DISPLAY_NAME, PD.column_value, PD.CODE, PD.UPDATED_BY, EMP.PLAN_UUID, EMP.FILE_UUID, PD.* 
from PAYROLL_DATA_HISTORY PD join EMPLOYEES EMP on PD.EMPLOYEE_UUID = EMP.EMPLOYEE_UUID 
where EMP.SOCIAL_SECURITY_NUMBER in ('<SSN>')
and PD.CODE is not null
order by EMP.PAYROLL_DATE, PD.EDIT_DATE, PD.EMPLOYEE_UUID, PD.DISPLAY_NAME;


--SOURCE ELIGIBILITY--
select EE.PAYROLL_DATE, EE.HOURS, EE.HR_CODE, SE.* from SOURCEELIGIBILITY SE
join EMPLOYEES EE on EE.EMPLOYEE_SNAPSHOT_ID = SE.EMPLOYEE_SNAPSHOT_ID
where EE.SOCIAL_SECURITY_NUMBER = '<SSN>'
order by EE.PAYROLL_DATE;


--service accumulator--
select EE.PAYROLL_DATE, EE.HOURS, EE.HR_CODE, SE.* from SERVICEACCUMULATOR SE
join EMPLOYEES EE on EE.EMPLOYEE_SNAPSHOT_ID = SE.EMPLOYEE_SNAPSHOT_ID
where EE.SOCIAL_SECURITY_NUMBER = '<SSN>'
order by EE.PAYROLL_DATE;

       
--Source Contribution data for employee       
select * from SOURCECONTRIBUTIONCALC SCC join EMPLOYEES EMP on EMP.EMPLOYEE_SNAPSHOT_ID = SCC.EMPLOYEE_SNAPSHOT_ID
where EMP.SOCIAL_SECURITY_NUMBER = '<SSN>';


--salary info for employee
select EMP.CREATION_SOURCE, EMP.IS_ADJUSTMENT, EMP.PAYROLL_DATE, EMP.SOCIAL_SECURITY_NUMBER, PD.EMPLOYEE_UUID, PD.DISPLAY_NAME, PD.column_value, PD.CODE
from PAYROLL_DATA PD join EMPLOYEES EMP on EMP.EMPLOYEE_UUID = PD.EMPLOYEE_UUID 
where EMP.SOCIAL_SECURITY_NUMBER like '<SSN>'
 order by EMP.PAYROLL_DATE, EMP.EMPLOYEE_UUID, PD.DISPLAY_NAME;
 

